name = "MyFirstPackage"
uuid = "57b0638b-19f0-48af-bd66-46638d7bad89"
authors = ["yuqingrong"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
